# Individuals configuration
[INDIVIDUALS]

# Observations configuration
[OBSERVATIONS]

# Captures configuration
[CAPTURE]

# Tracking devices configuration
[DEVICES]
    # The default columns name have to be those of the corresponding db table field
    DEFAULT_DISPLAYED_COLUMNS=["provider_name", "provider_device_id", "nomenclature_device_type_name", "referer_name", "last_individual_equipped_name", "meta_create_date"]