from .devices import TrackingDevices
from .captures import Capture, IndividualsCaptureObservations, CorRoleCapture
from .deployments import IndividualDeployments
from .individuals import register_individual_extensions

IndividualDeployments.register_capture_backref(Capture)
IndividualDeployments.register_individual_backref()
register_individual_extensions()
