from geonature.utils.env import db, ma
from marshmallow import fields, validates, validates_schema, ValidationError
from utils_flask_sqla.schema import SmartRelationshipsMixin

from pypnnomenclature.utils import NomenclaturesConverter
from pypnnomenclature.models import TNomenclatures
from geonature.core.gn_monitoring.models import TIndividuals

from .. import MODULE_CODE
from ..models import TrackingDevices, IndividualDeployments
from .utils import get_label, is_nomenclature_of_type


class DeploymentSchema(SmartRelationshipsMixin, ma.SQLAlchemyAutoSchema):
    class Meta:
        model = IndividualDeployments
        include_fk = True
        load_instance = True
        sqla_session = db.session
        include_relationships = True
        model_converter = NomenclaturesConverter
        feature_id = "id_deployment"

    id_deployment = ma.auto_field(dump_only=True)
    install_date = fields.DateTime(format="%Y-%m-%d", dump_only=True)
    removal_date = fields.DateTime(format="%Y-%m-%d", dump_only=True)
    meta_create_date = fields.Date(format="%Y-%m-%d", dump_only=True)
    meta_update_date = fields.Date(format="%Y-%m-%d", dump_only=True)

    # nomenclature_deployment_type/location are Nested by default (auto-generated by
    # NomenclaturesConverter, SmartRelationshipsMixin excludes them). Include them via
    # only=[*[f"+{n}" for n in IndividualDeployments.__nomenclatures__]] when instantiating.
    individual_name = fields.Method("get_individual_name", dump_only=True)
    tracking_device_info = fields.Method("get_tracking_device", dump_only=True)
    digitiser_name = fields.Method("get_digitiser", dump_only=True)
    deployment_type_name = fields.Method("get_deployment_type_name", dump_only=True)
    deployment_location_name = fields.Method("get_deployment_location_name", dump_only=True)

    __module_code__ = MODULE_CODE

    # Validators

    @validates("id_individual")
    def validate_individual(self, value, **kwargs):
        if db.session.get(TIndividuals, value) is None:
            raise ValidationError(f"The individual {value} does not exist.")
        return value

    @validates("id_tracking_device")
    def validate_tracking_device(self, value, **kwargs):
        if value is None:
            return value
        if db.session.get(TrackingDevices, value) is None:
            raise ValidationError(f"The tracking device {value} does not exist.")
        return value

    @validates("id_nomenclature_deployment_type")
    def validate_nomenclature_deployment_type(self, value, **kwargs):
        nomenclature = db.session.get(TNomenclatures, value)
        if nomenclature is None:
            raise ValidationError(f"The nomenclature {value} (deployment type) does not exist.")
        if not is_nomenclature_of_type(nomenclature, "TYPE_MARQUAGE"):
            raise ValidationError(
                f"The nomenclature {value} is not of the expected type (TYPE_MARQUAGE)."
            )
        return value

    @validates("id_nomenclature_deployment_location")
    def validate_nomenclature_deployment_location(self, value, **kwargs):
        nomenclature = db.session.get(TNomenclatures, value)
        if nomenclature is None:
            raise ValidationError(
                f"The nomenclature {value} (deployment location) does not exist."
            )
        if not is_nomenclature_of_type(nomenclature, "LOC_MARQUAGE"):
            raise ValidationError(
                f"The nomenclature {value} is not of the expected type (LOC_MARQUAGE)."
            )
        return value

    @validates_schema
    def validate_dates(self, data, **kwargs):
        """removal_date must be after install_date when both are present."""
        install = data.get("install_date")
        removal = data.get("removal_date")
        if install and removal and removal <= install:
            raise ValidationError(
                {"removal_date": ["removal date must be posterior to install date."]}
            )

    # Serialization

    def get_individual_name(self, obj):
        if obj.individual:
            name = obj.individual.individual_name
            if obj.individual.taxon and obj.individual.taxon.nom_vern:
                return f"{name} ({obj.individual.taxon.nom_vern})"
            return name
        return None

    def get_tracking_device(self, obj):
        if obj.tracking_device:
            return obj.tracking_device.device_label
        return None

    def get_digitiser(self, obj):
        if obj.digitiser:
            return f"{obj.digitiser.prenom_role} {obj.digitiser.nom_role}"
        return None

    def get_deployment_type_name(self, obj):
        return get_label(obj.nomenclature_deployment_type)

    def get_deployment_location_name(self, obj):
        return get_label(obj.nomenclature_deployment_location)


class IndividualDeploymentWriteSchema(DeploymentSchema):
    """Used to create/update a deployment under an individual's PUT"""

    __module_code__ = MODULE_CODE

    id_individual = fields.Integer(dump_only=True)
    id_digitiser = fields.Integer(dump_only=True)
    # Loadable here: the base schema marks them dump_only for read use.
    install_date = fields.DateTime(format="%Y-%m-%d")
    removal_date = fields.DateTime(format="%Y-%m-%d", allow_none=True, required=False)


class DeploymentWriteSchema(DeploymentSchema):
    """Used to create/update a deployment, standalone, not related to an individual."""

    __module_code__ = MODULE_CODE

    id_digitiser = fields.Integer(dump_only=True)
    install_date = fields.DateTime(format="%Y-%m-%d", allow_none=True, required=False)
    removal_date = fields.DateTime(format="%Y-%m-%d", allow_none=True, required=False)


class DeploymentSummarySchema(ma.Schema):
    id_individual = fields.Integer(dump_only=True)
    individual_name = fields.Method("get_individual_name", dump_only=True)
    install_date = fields.DateTime(format="%d-%m-%y", dump_only=True)
    removal_date = fields.DateTime(format="%d-%m-%y", dump_only=True)
    comment = fields.Method("get_comment", dump_only=True)

    __module_code__ = MODULE_CODE

    def get_individual_name(self, obj):
        if obj.individual:
            name = obj.individual.individual_name
            if obj.individual.taxon and obj.individual.taxon.nom_vern:
                return f"{name} ({obj.individual.taxon.nom_vern})"
            return name
        return None

    def get_comment(self, obj):
        if obj.comment:
            return obj.comment.replace("\n", "<br>")
        return None
