name: Lint

on: [push, pull_request]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Debug
        run: |
          pwd
          ls -la
          find . -name "requirements-dev.in"
      - name: Install dev dependencies
        run: pip install -r requirements-dev.in
      - name: Check formatting
        run: black --check ./backend/gn_module_individuals
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
      - name: Frontend code formatting check (Prettier)
        run: npm install prettier@~3.3 && npm run format:check
        working-directory: ./frontend