name: pytest

on:
  push:
    paths:
      - "backend/**"
    branches:
      - master
      - develop 
  pull_request:
    paths:
      - "backend/**"
    branches:
      - master
      - develop

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        geonature_ref: ["feat/manageIndividuals"] # Mettre version compatible
    uses: PnVanoise/GeoNature/.github/workflows/gn-module-pytest.yml@develop
    with:
      geonature_repo: pnvanoise/geonature
      geonature_ref: ${{ matrix.geonature_ref }}
      upload_coverage: true
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}