name: pytest

on:
  push:
    paths:
      - "backend/**"
    branches:
      - master
      - develop
  pull_request:
    paths:
      - "backend/**"
    branches:
      - master
      - develop
      - feat/capture

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        geonature_ref: ["feat/individuals"] # Mettre version compatible
    uses: PnX-SI/GeoNature/.github/workflows/gn-module-pytest.yml@develop
    with:
      geonature_ref: ${{ matrix.geonature_ref }}
      upload_coverage: true
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}